# SPDX-License-Identifier: GPL-2.0
# Minimal net/ Makefile for ARC upstream module builds.
# Only includes subdirs with modules enabled for this platform.

obj-y				+= netfilter/
obj-y				+= ipv4/
obj-y				+= ipv6/
obj-y				+= sched/
